# Capstone - Stage 2

* Grouping of Toronto Nieghborhoods based on the type of venues located in them.


## Task 1: Web Scraping for List of Communities in Toronto
## Import the necessary Libraries


In [1]:
import pandas as pd

## Loading Data from HTML
Pandas function read_HTML is used to load the table from a HTML page whose URL is provided to the function.

In [5]:
URL = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

df = pd.read_html(URL)

## Retaining only those neighborhoods where borough is asssigned

* We first copy the first table that was read by the pandas function into a new dataframe.
* Then we copy only those records where the borough column is not 'Not assigned' to a new dataframe.

* This new data frame will be our clean one for further processing.

In [6]:
odf = df[0]
df = odf[odf.Borough != 'Not assigned']
df

Postal Code  ...                                       Neighborhood
2           M3A  ...                                          Parkwoods
3           M4A  ...                                   Victoria Village
4           M5A  ...                          Regent Park, Harbourfront
5           M6A  ...                   Lawrence Manor, Lawrence Heights
6           M7A  ...        Queen's Park, Ontario Provincial Government
..          ...  ...                                                ...
160         M8X  ...      The Kingsway, Montgomery Road, Old Mill North
165         M4Y  ...                               Church and Wellesley
168         M7Y  ...  Business reply mail Processing Centre, South C...
169         M8Y  ...  Old Mill South, King's Mill Park, Sunnylea, Hu...
178         M8Z  ...  Mimico NW, The Queensway West, South of Bloor,...

[103 rows x 3 columns]

In [ ]:
df[df.Neighborhood == 'Not Assigned']

Empty DataFrame
Columns: [Postal Code, Borough, Neighborhood]
Index: []

## Data is already in the suggested format.
* As can be seen from the output in the above two cells, the data is already processed as per the instructions given for the assignment.

* The following cell shows how the said task could have been done had it been needed
* Here, for illustration, 'postal code' and 'Neighborhood' variables are combined with commas based on variable 'Borough'

In [7]:
df.groupby('Borough').aggregate({'Postal Code':', '.join,'Neighborhood':', '.join})

Postal Code                                       Neighborhood
Borough                                                                                                               
Central Toronto         M4N, M5N, M4P, M5P, M4R, M5R, M4S, M4T, M4V  Lawrence Park, Roselawn, Davisville North, For...
Downtown Toronto  M5A, M7A, M5B, M5C, M5E, M5G, M6G, M5H, M5J, M...  Regent Park, Harbourfront, Queen's Park, Ontar...
East Toronto                                M4E, M4K, M4L, M4M, M7Y  The Beaches, The Danforth West, Riverdale, Ind...
East York                                   M4B, M4C, M4G, M4H, M4J  Parkview Hill, Woodbine Gardens, Woodbine Heig...
Etobicoke         M9A, M9B, M9C, M9P, M9R, M8V, M9V, M8W, M9W, M...  Islington Avenue, Humber Valley Village, West ...
Mississauga                                                     M7R              Canada Post Gateway Processing Centre
North York        M3A, M4A, M6A, M3B, M6B, M3C, M2H, M3H, M2J, M...  Parkwoods, Victoria Village, Lawrence Manor, L...
Scarborough       M1B, M1C, M1E, M1G, M1H, M1J, M1K, M1L, M1M, M...  Malvern, Rouge, Rouge Hill, Port Union, Highla...
West Toronto                           M6H, M6J, M6K, M6P, M6R, M6S  Dufferin, Dovercourt Village, Little Portugal,...
York                                        M6C, M6E, M6M, M6N, M9N  Humewood-Cedarvale, Caledonia-Fairbanks, Del R...

In [ ]:
df.shape

(103, 3)

## Task 2: Adding the Latitude Longitude Information
* As was hinted in the instructions, the geocoder API was not reliable enough to get the latitude and longitude information.
* The following two cells show the attempt made at loading the required library and looping thourgh the rows of the data frame to put together lists of latitude and longitude of each postal code in the data frame.
* However, the API call was taking too much time and this approach  is abandoned.
* Thus the provided file was loaded and used instead.

In [8]:
!pip install geocoder
import geocoder

     |████████████████████████████████| 102kB 2.3MB/s 


In [9]:
for index, row in df.iterrows():
  ll = None
  la =[]
  lo =[]
  i=0
  while(ll is None):
    print('Attempt ',i)
    g = geocoder.google('{}, Toronto, Ontario'.format(row['Postal Code']))
    ll = g.latlng
    i+=1
  la.append(ll[0])
  lo.append(ll[1])

Attempt  0
Attempt  1
Attempt  2
Attempt  3
Attempt  4
Attempt  5
Attempt  6
Attempt  7
Attempt  8
Attempt  9
Attempt  10
Attempt  11
Attempt  12
Attempt  13
Attempt  14
Attempt  15
Attempt  16
Attempt  17
Attempt  18
Attempt  19
Attempt  20
Attempt  21
Attempt  22
Attempt  23
Attempt  24
Attempt  25
Attempt  26
Attempt  27
Attempt  28
Attempt  29
Attempt  30
Attempt  31
Attempt  32
Attempt  33
Attempt  34
Attempt  35
Attempt  36
Attempt  37
Attempt  38
Attempt  39
Attempt  40
Attempt  41
Attempt  42
Attempt  43
Attempt  44
Attempt  45
Attempt  46
Attempt  47
Attempt  48
Attempt  49
Attempt  50
Attempt  51
Attempt  52
Attempt  53
Attempt  54
Attempt  55
Attempt  56
Attempt  57
Attempt  58
Attempt  59
Attempt  60
Attempt  61
Attempt  62
Attempt  63
Attempt  64
Attempt  65
Attempt  66
Attempt  67
Attempt  68
Attempt  69
Attempt  70
Attempt  71
Attempt  72
Attempt  73
Attempt  74
Attempt  75
Attempt  76
Attempt  77
Attempt  78
Attempt  79
Attempt  80
Attempt  81
Attempt  82
Attempt  83
At

KeyboardInterrupt: ignored

In [28]:
latlng = pd.read_csv('/content/Geospatial_Coordinates.csv')
latlng.head(10)

Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476
5         M1J  43.744734 -79.239476
6         M1K  43.727929 -79.262029
7         M1L  43.711112 -79.284577
8         M1M  43.716316 -79.239476
9         M1N  43.692657 -79.264848

## Joining the postal code and location names with the corresponding latitude and longitude data.
* Pandas merge function is used to join the community names in dataframe 'df' with the latitude longitude data in 'latlng' data frame based on the 'Postal Code' column which is common in the two tables.

In [40]:
fdf = pd.merge(df,latlng, on='Postal Code')
fdf

Postal Code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
5           M9A         Etobicoke   
6           M1B       Scarborough   
7           M3B        North York   
8           M4B         East York   
9           M5B  Downtown Toronto   
10          M6B        North York   
11          M9B         Etobicoke   
12          M1C       Scarborough   
13          M3C        North York   
14          M4C         East York   
15          M5C  Downtown Toronto   
16          M6C              York   
17          M9C         Etobicoke   
18          M1E       Scarborough   
19          M4E      East Toronto   
20          M5E  Downtown Toronto   
21          M6E              York   
22          M1G       Scarborough   
23          M4G         East York   
24          M5G  Downtown Toronto   
25          M6G  Downtown Toronto   
26          M1H       Scarborough   
27          M2H        North York   
28          M3H        North York   
29          M4H         East York   
30          M5H  Downtown Toronto   
31          M6H      West Toronto   
32          M1J       Scarborough   
33          M2J        North York   
34          M3J        North York   
35          M4J         East York   
36          M5J  Downtown Toronto   
37          M6J      West Toronto   
38          M1K       Scarborough   
39          M2K        North York   
40          M3K        North York   
41          M4K      East Toronto   
42          M5K  Downtown Toronto   
43          M6K      West Toronto   
44          M1L       Scarborough   
45          M2L        North York   
46          M3L        North York   
47          M4L      East Toronto   
48          M5L  Downtown Toronto   
49          M6L        North York   
50          M9L        North York   
51          M1M       Scarborough   
52          M2M        North York   
53          M3M        North York   
54          M4M      East Toronto   
55          M5M        North York   
56          M6M              York   
57          M9M        North York   
58          M1N       Scarborough   
59          M2N        North York   
60          M3N        North York   
61          M4N   Central Toronto   
62          M5N   Central Toronto   
63          M6N              York   
64          M9N              York   
65          M1P       Scarborough   
66          M2P        North York   
67          M4P   Central Toronto   
68          M5P   Central Toronto   
69          M6P      West Toronto   
70          M9P         Etobicoke   
71          M1R       Scarborough   
72          M2R        North York   
73          M4R   Central Toronto   
74          M5R   Central Toronto   
75          M6R      West Toronto   
76          M7R       Mississauga   
77          M9R         Etobicoke   
78          M1S       Scarborough   
79          M4S   Central Toronto   
80          M5S  Downtown Toronto   
81          M6S      West Toronto   
82          M1T       Scarborough   
83          M4T   Central Toronto   
84          M5T  Downtown Toronto   
85          M1V       Scarborough   
86          M4V   Central Toronto   
87          M5V  Downtown Toronto   
88          M8V         Etobicoke   
89          M9V         Etobicoke   
90          M1W       Scarborough   
91          M4W  Downtown Toronto   
92          M5W  Downtown Toronto   
93          M8W         Etobicoke   
94          M9W         Etobicoke   
95          M1X       Scarborough   
96          M4X  Downtown Toronto   
97          M5X  Downtown Toronto   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                          Neighborhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656

## Task 3: Clustering of Communities

* In order to reduce the computational complexity, the analysis is limited to only the neighborhoods in boroughs whose names contain 'Toronto'
* A new data frame is created with only those boroughs which have 'Toronto' in their name.


In [56]:
Boro = fdf[fdf['Borough'].str.contains('Toronto')].reset_index(drop=True)
Boro

Postal Code           Borough  \
0          M5A  Downtown Toronto   
1          M7A  Downtown Toronto   
2          M5B  Downtown Toronto   
3          M5C  Downtown Toronto   
4          M4E      East Toronto   
5          M5E  Downtown Toronto   
6          M5G  Downtown Toronto   
7          M6G  Downtown Toronto   
8          M5H  Downtown Toronto   
9          M6H      West Toronto   
10         M5J  Downtown Toronto   
11         M6J      West Toronto   
12         M4K      East Toronto   
13         M5K  Downtown Toronto   
14         M6K      West Toronto   
15         M4L      East Toronto   
16         M5L  Downtown Toronto   
17         M4M      East Toronto   
18         M4N   Central Toronto   
19         M5N   Central Toronto   
20         M4P   Central Toronto   
21         M5P   Central Toronto   
22         M6P      West Toronto   
23         M4R   Central Toronto   
24         M5R   Central Toronto   
25         M6R      West Toronto   
26         M4S   Central Toronto   
27         M5S  Downtown Toronto   
28         M6S      West Toronto   
29         M4T   Central Toronto   
30         M5T  Downtown Toronto   
31         M4V   Central Toronto   
32         M5V  Downtown Toronto   
33         M4W  Downtown Toronto   
34         M5W  Downtown Toronto   
35         M4X  Downtown Toronto   
36         M5X  Downtown Toronto   
37         M4Y  Downtown Toronto   
38         M7Y      East Toronto   

                                         Neighborhood   Latitude  Longitude  
0                           Regent Park, Harbourfront  43.654260 -79.360636  
1         Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
2                            Garden District, Ryerson  43.657162 -79.378937  
3                                      St. James Town  43.651494 -79.375418  
4                                         The Beaches  43.676357 -79.293031  
5                                         Berczy Park  43.644771 -79.373306  
6                                  Central Bay Street  43.657952 -79.387383  
7                                            Christie  43.669542 -79.422564  
8                            Richmond, Adelaide, King  43.650571 -79.384568  
9                        Dufferin, Dovercourt Village  43.669005 -79.442259  
10  Harbourfront East, Union Station, Toronto Islands  43.640816 -79.381752  
11                           Little Portugal, Trinity  43.647927 -79.419750  
12                       The Danforth West, Riverdale  43.679557 -79.352188  
13           Toronto Dominion Centre, Design Exchange  43.647177 -79.381576  
14       Brockton, Parkdale Village, Exhibition Place  43.636847 -79.428191  
15                     India Bazaar, The Beaches West  43.668999 -79.315572  
16                     Commerce Court, Victoria Hotel  43.648198 -79.379817  
17                                    Studio District  43.659526 -79.340923  
18                                      Lawrence Park  43.728020 -79.388790  
19                                           Roselawn  43.711695 -79.416936  
20                                   Davisville North  43.712751 -79.390197  
21    Forest Hill North & West, Forest Hill Road Park  43.696948 -79.411307  
22                      High Park, The Junction South  43.661608 -79.464763  
23                  North Toronto West, Lawrence Park  43.715383 -79.405678  
24                The Annex, North Midtown, Yorkville  43.672710 -79.405678  
25                             Parkdale, Roncesvalles  43.648960 -79.456325  
26                                         Davisville  43.704324 -79.388790  
27                     University of Toronto, Harbord  43.662696 -79.400049  
28                                 Runnymede, Swansea  43.651571 -79.484450  
29                        Moore Park, Summerhill East  43.689574 -79.383160  
30          Kensington Market, Chinatown, Grange Park  43.653206 -79.400049  
31  Summerhill West, Rathnelly, South Hill, Forest...  43.686412 -

## Creating a new data frame with one row for each neighborhood
* The data frame now contains one row per each borough which is a collection of one or more neighborhoods.
* Since we are looking to cluster the neighborhoods rather than the borough, we first seperate out the individual neighborhoods in each borough and a new dataframe is created with one row for each neighborhood.
* Simultaneously, the latitude and longitude information for each neighborhood is retrieved from the geocoder API and is added to the corresponding record.
* There are a total of 71 neighborhoods in Toronto. 

In [105]:
Toronto_data = pd.DataFrame(columns=['Borough', 'Neighborhood', 'Latitude', 'Longitude'])

for ind, boro in Boro.iterrows():
    borough =  boro['Borough'] 

    
    for neigh in boro['Neighborhood'].split(','):

        address = '{}, Toronto, Ontario'.format(neigh)

        location = geolocator.geocode(address)
        try:
           latitude = location.latitude
           longitude = location.longitude
           Toronto_data = Toronto_data.append({'Borough': borough,
                                          'Neighborhood': neigh,
                                          'Latitude': latitude,
                                          'Longitude': longitude}, ignore_index=True)
        except:
           continue

Toronto_data

Borough              Neighborhood   Latitude  Longitude
0   Downtown Toronto               Regent Park  43.660706 -79.360457
1   Downtown Toronto              Harbourfront  43.640080 -79.380150
2   Downtown Toronto              Queen's Park  43.659659 -79.390340
3   Downtown Toronto           Garden District  43.656500 -79.377114
4   Downtown Toronto                   Ryerson  43.658469 -79.378993
5   Downtown Toronto            St. James Town  43.669403 -79.372704
6       East Toronto               The Beaches  43.671024 -79.296712
7   Downtown Toronto               Berczy Park  43.647984 -79.375396
8   Downtown Toronto                  Christie  43.664111 -79.418405
9   Downtown Toronto                  Richmond  43.812589 -79.263370
10  Downtown Toronto                  Adelaide  43.650823 -79.377936
11  Downtown Toronto                      King  43.648949 -79.377754
12      West Toronto                  Dufferin  43.660202 -79.435719
13      West Toronto        Dovercourt Village  43.665307 -79.432636
14  Downtown Toronto         Harbourfront East  43.640080 -79.380150
15  Downtown Toronto             Union Station  43.644693 -79.380132
16  Downtown Toronto           Toronto Islands  43.623054 -79.394316
17      West Toronto           Little Portugal  43.647413 -79.431116
18      West Toronto                   Trinity  43.665302 -79.395252
19      East Toronto         The Danforth West  43.686433 -79.300355
20      East Toronto                 Riverdale  43.665470 -79.352594
21  Downtown Toronto   Toronto Dominion Centre  43.647377 -79.381372
22  Downtown Toronto           Design Exchange  43.647741 -79.380115
23      West Toronto                  Brockton  43.650917 -79.440022
24      West Toronto          Parkdale Village  43.640495 -79.436897
25      West Toronto          Exhibition Place  43.633538 -79.417711
26      East Toronto              India Bazaar  43.672223 -79.323503
27      East Toronto          The Beaches West  43.671024 -79.296712
28  Downtown Toronto            Commerce Court  43.648095 -79.379025
29  Downtown Toronto            Victoria Hotel  43.669469 -79.373268
30      East Toronto           Studio District  43.649585 -79.390683
31   Central Toronto             Lawrence Park  43.729199 -79.403252
32   Central Toronto                  Roselawn  43.699456 -79.454616
33   Central Toronto          Davisville North  43.697936 -79.397291
34   Central Toronto  Forest Hill North & West  43.701028 -79.425600
35   Central Toronto     Forest Hill Road Park  43.688379 -79.404009
36      West Toronto                 High Park  43.653867 -79.466864
37      West Toronto        The Junction South  43.665478 -79.470352
38   Central Toronto        North Toronto West  43.646547 -79.419526
39   Central Toronto             Lawrence Park  43.729199 -79.403252
40   Central Toronto                 The Annex  43.670338 -79.407117
41   Central Toronto             North Midtown  43.705736 -79.397567
42   Central Toronto                 Yorkville  43.671386 -79.390168
43      West Toronto                  Parkdale  43.640495 -79.436897
44      West Toronto              Roncesvalles  43.651443 -79.451038
45   Central Toronto                Davisville  43.697936 -79.397291
46  Downtown Toronto     University of Toronto  43.663462 -79.397760
47  Downtown Toronto                   Harbord  43.661512 -79.414391
48      West Toronto                 Runnymede  43.651703 -79.475998
49      West Toronto                   Swansea  43.644940 -79.478313
50   Central Toronto                Moore Park  43.690388 -79.383297
51   Central Toronto           Summerhill East  43.681678 -79.390504
52  Downtown Toronto         Kensington Market  43.655214 -79.402260
53  Downtown Toronto                 Chinatown  43.652924 -79.398032
54  Downtown Toronto               Grange Park  43.652197 -79.392319
55   Central Toronto           Summerhill West  43.681678 -79.390504
56   Central Toronto                 Rathnelly  43.678395 -79.400822
57   Centra

## Additional Libraries
* Import the required additional libraries for clustering and plotting.

In [30]:

import numpy as np # library to handle data in a vectorized manner

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Libraries imported.


## Plotting of Neighborhoods on Map
* A map is generated for the Toronto area and the locations of neighborhoods are marked on the map along with the labels.

In [31]:
address = 'Toronto, Ontario'

geolocator = Nominatim(user_agent="TO_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Ontario are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Ontario are 43.6534817, -79.3839347.


In [106]:
Toronto_map = folium.Map(location=[latitude, longitude], zoom_start=12)

# add markers to map
for lat, lng, label in zip(Toronto_data['Latitude'], Toronto_data['Longitude'], Toronto_data['Neighborhood']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(Toronto_map)  

In [107]:
Toronto_map

## Set the Credentials required for accessing data from Foursquares.

* Client ID and secret are set in this cell but they are now removed to protect privacy.

In [96]:
CLIENT_ID = '??????' # your Foursquare ID
CLIENT_SECRET = '*******' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version
radius = 500
LIMIT=100

print('Four Square credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Four Square credentails:
CLIENT_ID: LGIKCWX0K4JEFA2X01F1Z0ELZUHNBF53CF3DFM1KOET2YIYN
CLIENT_SECRET:5SMLVSN3PYAKN250EUOYL2CUYOQ0211XNYG4MU3BFIZVACBN


## Retrieving information from Foursquare
* The function in the following cell is adapted from the ungraded assignment.
* The function is invoked to get venues in vicinity of each neighborhood.

In [110]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [ ]:
Toronto_venues = getNearbyVenues(names=Toronto_data['Neighborhood'],
                                   latitudes=Toronto_data['Latitude'],
                                   longitudes=Toronto_data['Longitude']
                                  )

## Summary of Venues data
* There are a total of 3592 Venues.
* Neighborhood wise counts of events are presented in the subsequent cell.
* There are a total of 302 unique categories of venues in Toronto.

In [149]:
print(Toronto_venues.shape)
Toronto_venues.head(15)

(3592, 7)


Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0   Regent Park              43.660706              -79.360457   
1   Regent Park              43.660706              -79.360457   
2   Regent Park              43.660706              -79.360457   
3   Regent Park              43.660706              -79.360457   
4   Regent Park              43.660706              -79.360457   
5   Regent Park              43.660706              -79.360457   
6   Regent Park              43.660706              -79.360457   
7   Regent Park              43.660706              -79.360457   
8   Regent Park              43.660706              -79.360457   
9   Regent Park              43.660706              -79.360457   
10  Regent Park              43.660706              -79.360457   
11  Regent Park              43.660706              -79.360457   
12  Regent Park              43.660706              -79.360457   
13  Regent Park              43.660706              -79.360457   
14  Regent Park              43.660706              -79.360457   

                         Venue  Venue Latitude  Venue Longitude  \
0   Regent Park Aquatic Centre       43.660600       -79.361392   
1              Sumach Espresso       43.658135       -79.359515   
2             Daniels Spectrum       43.660137       -79.361808   
3                   Thai To Go       43.663418       -79.360710   
4              Paintbox Bistro       43.660050       -79.362855   
5                     Qi sushi       43.662552       -79.364258   
6     Dominion Pub and Kitchen       43.656919       -79.358967   
7                    Sukhothai       43.658444       -79.365681   
8       Toronto Humane Society       43.657698       -79.356583   
9               I Love Churros       43.658364       -79.365583   
10      Mercedes-Benz Downtown       43.661431       -79.356585   
11                 Regent Park       43.660383       -79.361810   
12          Shoppers Drug Mart       43.660204       -79.361332   
13                      Vistek       43.657046       -79.359667   
14                     Wendy’s       43.660403       -79.360629   

           Venue Category  
0                    Pool  
1             Coffee Shop  
2   Performing Arts Venue  
3         Thai Restaurant  
4              Restaurant  
5        Sushi Restaurant  
6                     Pub  
7         Thai Restaurant  
8          Animal Shelter  
9              Food Truck  
10        Auto Dealership  
11                   Park  
12               Pharmacy  
13      Electronics Store  
14   Fast Food Restaurant

In [114]:
Toronto_venues[['Neighborhood','Venue']].groupby('Neighborhood').count()

Venue
Neighborhood                   
 Adelaide                   100
 Bathurst Quay               25
 Cabbagetown                 49
 Chinatown                   64
 Deer Park                   57
 Design Exchange            100
 Dovercourt Village           9
 Exhibition Place            41
 Forest Hill Road Park        7
 Forest Hill SE               5
 Grange Park                100
 Harbord                     73
 Harbourfront               100
 Harbourfront West          100
 Island airport              12
 King                       100
 King and Spadina            72
 Lawrence Park               51
 North Midtown               73
 Parkdale Village            44
 Rathnelly                   15
 Riverdale                   29
 Roncesvalles                40
 Ryerson                    100
 South Hill                  26
 South Niagara               49
 Summerhill East             40
 Swansea                      4
 The Beaches West            49
 The Junction South          57
 Toronto Islands              4
 Trinity                     42
 Underground city            11
 Union Station               54
 Victoria Hotel              37
 Yorkville                  100
Berczy Park                 100
Brockton                     18
CN Tower                     59
Christie                     57
Church and Wellesley         74
Commerce Court              100
Davisville                   42
Davisville North             42
Dufferin                     44
First Canadian Place        100
Forest Hill North & West     20
Garden District              65
Harbourfront East           100
High Park                    12
India Bazaar                 35
Kensington Market            87
Lawrence Park                51
Little Portugal              37
Moore Park                    3
North Toronto West           52
Parkdale                     44
Queen's Park                 71
Regent Park                  21
Richmond                      3
Rosedale                      3
Roselawn                     11
Runnymede                    42
St. James Town               66
Studio District             100
Summerhill West              40
The Annex                    44
The Beaches                  49
The Danforth West            30
Toronto Dominion Centre     100
University of Toronto        31

In [115]:
print('There are',len(Toronto_venues['Venue Category'].unique()), 'unique types of venues in Toronto Neighborhoods')

There are 302 unique types of venues in Toronto Neighborhoods


## Data Preparation and Exploratory Data Analysis for Clustering
* A dummy variable is created for the categorical variable 'Venue Category' and it is concatenated with the 'Neighborhood' variable in the venues data frame.
* When creating dummy variables for the 'Venue Category' it was observed that there is category called 'Neighborhood' and to avoid a duplicate column name, the original 'Neighborhood' is renamed a 'Hood'.
* The new data frame called 'Toront_OH' has 303 columns (one for Neighborhood named 'Hood' and other 302 for each unique category) and 3592 records (one for each venue).

In [128]:
Toronto_OH =  pd.concat([pd.DataFrame.from_dict({'Hood':Toronto_venues['Neighborhood']}),
                          pd.get_dummies(Toronto_venues[['Venue Category']], prefix="", prefix_sep="")]
                        ,axis=1)

In [129]:
Toronto_OH.head()

Hood  Accessories Store  Afghan Restaurant  African Restaurant  \
0  Regent Park                  0                  0                   0   
1  Regent Park                  0                  0                   0   
2  Regent Park                  0                  0                   0   
3  Regent Park                  0                  0                   0   
4  Regent Park                  0                  0                   0   

   Airport  Airport Food Court  Airport Lounge  Airport Service  \
0        0                   0               0                0   
1        0                   0               0                0   
2        0                   0               0                0   
3        0                   0               0                0   
4        0                   0               0                0   

   Airport Terminal  American Restaurant  Animal Shelter  Antique Shop  \
0                 0                    0               0             0   
1                 0                    0               0             0   
2                 0                    0               0             0   
3                 0                    0               0             0   
4                 0                    0               0             0   

   Aquarium  Argentinian Restaurant  Art Gallery  Art Museum  \
0         0                       0            0           0   
1         0                       0            0           0   
2         0                       0            0           0   
3         0                       0            0           0   
4         0                       0            0           0   

   Arts & Crafts Store  Arts & Entertainment  Asian Restaurant  \
0                    0                     0                 0   
1                    0                     0                 0   
2                    0                     0                 0   
3                    0                     0                 0   
4                    0                     0                 0   

   Athletics & Sports  Auto Dealership  Auto Workshop  BBQ Joint  Bagel Shop  \
0                   0                0              0          0           0   
1                   0                0              0          0           0   
2                   0                0              0          0           0   
3                   0                0              0          0           0   
4                   0                0              0          0           0   

   Bakery  Bank  Bar  Baseball Field  Baseball Stadium  Basketball Stadium  \
0       0     0    0               0                 0                   0   
1       0     0    0               0                 0                   0   
2       0     0    0               0                 0                   0   
3       0     0    0               0                 0                   0   
4       0     0    0               0                 0                   0   

   Beach  Beach Bar  Bed & Breakfast  Beer Bar  Beer Store  \
0      0          0                0         0           0   
1      0          0                0         0           0   
2      0          0                0         0           0   
3      0          0                0         0           0   
4      0          0                0         0           0   

   Belgian Restaurant  Bike Rental / Bike Share  Bike Shop  Bike Trail  \
0                   0                         0          0           0   
1                   0                         0          0           0   
2                   0                         0          0           0   
3                   0                         0          0           0   
4                   0                         0          0           0   

   Bistro  Board Shop  Boat or Ferry  Bookstore  Boutique  Bowling Alley  \
0       0           0              0          0         0              0   
1  

In [130]:
print(Toronto_OH.shape)

(3592, 303)


## Frequency of each type of venue in Neighborhoods
* Group_by function is used to find the frequency of each type of venue in the Neighborhood.
* There are 71 records in the new data frame.

In [131]:
Toronto_grouped = Toronto_OH.groupby('Hood').mean().reset_index()
Toronto_grouped

Hood  Accessories Store  Afghan Restaurant  \
0                   Adelaide           0.000000           0.000000   
1              Bathurst Quay           0.000000           0.000000   
2                Cabbagetown           0.000000           0.000000   
3                  Chinatown           0.000000           0.000000   
4                  Deer Park           0.000000           0.000000   
5            Design Exchange           0.000000           0.000000   
6         Dovercourt Village           0.000000           0.000000   
7           Exhibition Place           0.000000           0.000000   
8      Forest Hill Road Park           0.000000           0.000000   
9             Forest Hill SE           0.000000           0.000000   
10               Grange Park           0.000000           0.000000   
11                   Harbord           0.000000           0.000000   
12              Harbourfront           0.000000           0.000000   
13         Harbourfront West           0.000000           0.000000   
14            Island airport           0.000000           0.000000   
15                      King           0.000000           0.000000   
16          King and Spadina           0.000000           0.000000   
17             Lawrence Park           0.000000           0.000000   
18             North Midtown           0.000000           0.000000   
19          Parkdale Village           0.022727           0.000000   
20                 Rathnelly           0.000000           0.000000   
21                 Riverdale           0.000000           0.000000   
22              Roncesvalles           0.000000           0.000000   
23                   Ryerson           0.000000           0.000000   
24                South Hill           0.000000           0.000000   
25             South Niagara           0.020408           0.000000   
26           Summerhill East           0.000000           0.000000   
27                   Swansea           0.000000           0.000000   
28          The Beaches West           0.000000           0.000000   
29        The Junction South           0.000000           0.000000   
30           Toronto Islands           0.000000           0.000000   
31                   Trinity           0.000000           0.000000   
32          Underground city           0.000000           0.000000   
33             Union Station           0.000000           0.000000   
34            Victoria Hotel           0.000000           0.000000   
35                 Yorkville           0.000000           0.000000   
36               Berczy Park           0.000000           0.000000   
37                  Brockton           0.000000           0.000000   
38                  CN Tower           0.000000           0.000000   
39                  Christie           0.000000           0.000000   
40      Church and Wellesley           0.000000           0.013514   
41            Commerce Court           0.000000           0.000000   
42                Davisville           0.000000           0.000000   
43          Davisville North           0.000000           0.000000   
44                  Dufferin           0.000000           0.000000   
45      First Canadian Place           0.000000           0.000000   
46  Forest Hill North & West           0.000000           0.000000   
47           Garden District           0.000000           0.000000   
48         Harbourfront East           0.000000           0.000000   
49                 High Park           0.000000           0.000000   
50              India Bazaar           0.000000           0.000000   
51         Kensington Market           0.000000           0.000000   
52             Lawrence Park           0.000000           0.000000   
53           Little Portugal           0.000000           0.000000   
54                Moore Park           0.000000           0.000000   
55        North Toronto West           0.000000           0.000000   
56                  Parkdale      

## Top 5 types of Venues in each Neighborhood
* For each of the 71 venues the top 5 most common types of venues are printed by adopting the same procedure as was used in the ungraded assignment.

In [132]:
num_top_venues = 5

for hood in Toronto_grouped['Hood']:
    print("----"+hood+"----")
    temp = Toronto_grouped[Toronto_grouped['Hood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

---- Adelaide----
                 venue  freq
0          Coffee Shop  0.07
1                  Gym  0.05
2                 Café  0.05
3           Restaurant  0.05
4  American Restaurant  0.04


---- Bathurst Quay----
          venue  freq
0   Coffee Shop  0.16
1          Café  0.12
2          Park  0.08
3  Dance Studio  0.04
4        Tunnel  0.04


---- Cabbagetown----
                venue  freq
0                Café  0.08
1          Restaurant  0.06
2         Coffee Shop  0.06
3  Chinese Restaurant  0.04
4          Beer Store  0.04


---- Chinatown----
                           venue  freq
0                   Dessert Shop  0.06
1                           Café  0.06
2             Mexican Restaurant  0.05
3  Vegetarian / Vegan Restaurant  0.05
4                  Grocery Store  0.03


---- Deer Park----
                venue  freq
0         Coffee Shop  0.12
1  Italian Restaurant  0.07
2     Thai Restaurant  0.05
3       Grocery Store  0.05
4    Sushi Restaurant  0.05


---- Design Ex

## Table of 10 most common types of venues in Neighborhoods.
* The following cells are taken from the ungraded assignment to make a table contains the top 10 venue categories available close to the neighborhoods.

In [133]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [135]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = Toronto_grouped['Hood']

for ind in np.arange(Toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(Toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
0        Adelaide           Coffee Shop                  Café   
1   Bathurst Quay           Coffee Shop                  Café   
2     Cabbagetown                  Café           Coffee Shop   
3       Chinatown                  Café          Dessert Shop   
4       Deer Park           Coffee Shop    Italian Restaurant   

  3rd Most Common Venue          4th Most Common Venue 5th Most Common Venue  \
0                   Gym                     Restaurant             Gastropub   
1                  Park                          Diner       Harbor / Marina   
2            Restaurant                         Bakery                   Pub   
3    Mexican Restaurant  Vegetarian / Vegan Restaurant        Clothing Store   
4      Sushi Restaurant                  Grocery Store       Thai Restaurant   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0   American Restaurant        Cosmetics Shop    Seafood Restaurant   
1  Caribbean Restaurant                  Bank      Ramen Restaurant   
2     Indian Restaurant    Italian Restaurant                 Diner   
3                   Bar                Bakery           Pizza Place   
4            Bagel Shop        Sandwich Place                  Café   

  9th Most Common Venue 10th Most Common Venue  
0   Japanese Restaurant         Breakfast Spot  
1      Sculpture Garden    Japanese Restaurant  
2    Chinese Restaurant    Japanese Restaurant  
3           Coffee Shop            Art Gallery  
4            Restaurant                    Pub

## Clustering
* Same procedure, as was applied in the ungraded assignment, is used to perform the clustering.
  * The number of clusters is also taken as 5.
  * The cluster labels were added back to the venues data frame as well as to the data frame which has the top 10 most common venue types for each neighborhood.

In [138]:
# set number of clusters
kclusters = 5

Toronto_grouped_clustering = Toronto_grouped.drop('Hood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(Toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:30] 

array([2, 2, 0, 0, 2, 2, 2, 0, 4, 3, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 3, 0,
       0, 2, 0, 0, 0, 1, 0, 0], dtype=int32)

In [139]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

Toronto_merged = Toronto_data

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
Toronto_merged = Toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

Toronto_merged.head() # check the last columns!

Borough     Neighborhood   Latitude  Longitude  Cluster Labels  \
0  Downtown Toronto      Regent Park  43.660706 -79.360457               2   
1  Downtown Toronto     Harbourfront  43.640080 -79.380150               2   
2  Downtown Toronto     Queen's Park  43.659659 -79.390340               2   
3  Downtown Toronto  Garden District  43.656500 -79.377114               0   
4  Downtown Toronto          Ryerson  43.658469 -79.378993               2   

  1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0           Coffee Shop       Thai Restaurant                  Pool   
1           Coffee Shop                  Café            Restaurant   
2           Coffee Shop                  Café        Sandwich Place   
3        Clothing Store           Coffee Shop            Restaurant   
4           Coffee Shop        Clothing Store          Burger Joint   

  4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0     Electronics Store            Beer Store            Food Truck   
1                 Hotel    Italian Restaurant           Pizza Place   
2    Italian Restaurant   Japanese Restaurant     French Restaurant   
3                 Hotel        Sandwich Place                Bakery   
4      Ramen Restaurant   Japanese Restaurant                  Café   

  7th Most Common Venue      8th Most Common Venue 9th Most Common Venue  \
0      Sushi Restaurant                 Restaurant       Auto Dealership   
1        Sandwich Place                 Sports Bar                  Bank   
2       Thai Restaurant            Bubble Tea Shop    Chinese Restaurant   
3   Japanese Restaurant                   Tea Room               Theater   
4                 Diner  Middle Eastern Restaurant                Bakery   

  10th Most Common Venue  
0                    Pub  
1       Sushi Restaurant  
2         Discount Store  
3       Ramen Restaurant  
4               Tea Room

## Visualization of the Clusters on the Map
* The neighbors are once again plotted on the Map of Toronto area using the approach used in the ungraded assignment.
* This time, the marker color signifies the cluster membership and the label also containes the cluster label.

In [141]:
# create map
address = 'Toronto, Ontario'
geolocator = Nominatim(user_agent="TO_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(Toronto_merged['Latitude'], Toronto_merged['Longitude'], Toronto_merged['Neighborhood'], Toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster+1), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

## List of Clusters
* The following cells print the members of each cluster.
* Cluster 1 has 39 Neighborhoods.
* Cluster 2 has 2 Neighborhoods.
* Cluster 3 has 25 Neighborhoods.
* Cluster 4 has 5 Neighborhoods.
* Cluster 5 has 1 Neighborhood.

In [151]:
Cluster1 = Toronto_merged.loc[Toronto_merged['Cluster Labels'] == 0, Toronto_merged.columns[[1] + list(range(5, Toronto_merged.shape[1]))]]

print('Cluster 1 has the following', Cluster1.shape[0],'Neighborhoods')
Cluster1

Cluster 1 has the following 39 Neighborhoods


Neighborhood  1st Most Common Venue  \
3            Garden District         Clothing Store   
6                The Beaches                  Beach   
8                   Christie      Korean Restaurant   
12                  Dufferin                    Bar   
17           Little Portugal                    Bar   
19         The Danforth West            Coffee Shop   
20                 Riverdale  Vietnamese Restaurant   
23                  Brockton                    Bar   
24          Parkdale Village     Tibetan Restaurant   
25          Exhibition Place             Theme Park   
26              India Bazaar      Indian Restaurant   
27          The Beaches West                  Beach   
30           Studio District            Coffee Shop   
31             Lawrence Park       Sushi Restaurant   
32                  Roselawn         Discount Store   
33          Davisville North     Italian Restaurant   
34  Forest Hill North & West            Pizza Place   
36                 High Park      Convenience Store   
37        The Junction South            Coffee Shop   
38        North Toronto West                    Bar   
39             Lawrence Park       Sushi Restaurant   
40                 The Annex            Pizza Place   
41             North Midtown            Coffee Shop   
42                 Yorkville            Coffee Shop   
43                  Parkdale     Tibetan Restaurant   
44              Roncesvalles                   Café   
45                Davisville     Italian Restaurant   
46     University of Toronto                   Café   
47                   Harbord      Korean Restaurant   
51           Summerhill East     Italian Restaurant   
52         Kensington Market                   Café   
53                 Chinatown                   Café   
54               Grange Park            Coffee Shop   
55           Summerhill West     Italian Restaurant   
57                South Hill         Sandwich Place   
64             South Niagara            Yoga Studio   
65            Island airport         Airport Lounge   
68               Cabbagetown                   Café   
70          Underground city            Fish Market   

            2nd Most Common Venue   3rd Most Common Venue  \
3                     Coffee Shop              Restaurant   
6                     Pizza Place                Tea Room   
8                     Coffee Shop            Cocktail Bar   
12                         Bakery             Coffee Shop   
17                           Café             Coffee Shop   
19                  Grocery Store                Bus Line   
20             Chinese Restaurant                  Bakery   
23          Vietnamese Restaurant                    Park   
24                         Bakery       Indian Restaurant   
25                 Soccer Stadium     Arts & Crafts Store   
26                           Café           Grocery Store   
27                    Pizza Place                Tea Room   
30                 Clothing Store                   Hotel   
31                         Bakery      Italian Restaurant   
32                    Coffee Shop  Furniture / Home Store   
33               Sushi Restaurant             Coffee Shop   
34                      Gastropub                   Trail   
36                    Pizza Place    Gym / Fitness Center   
37             Italian Restaurant                     Bar   
38  Vegetarian / Vegan Restaurant              Restaurant   
39                         Bakery      Italian Restaurant   
40                    Coffee Shop                  Bistro   
41             Italian Restaurant                     Pub   
42                       Boutique      Italian Restaurant   
43                         Bakery       Indian Restaurant   
44                      Gift Shop          Breakfast Spot   
45               Sushi Restaurant             Coffee Shop   
46                           Park               Bookstore   
47                           Park             

In [152]:
Cluster2 = Toronto_merged.loc[Toronto_merged['Cluster Labels'] == 1, Toronto_merged.columns[[1] + list(range(5, Toronto_merged.shape[1]))]]

print('Cluster 2 has the following', Cluster2.shape[0],'Neighborhoods')
Cluster2

Cluster 2 has the following 2 Neighborhoods


Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
49      Swansea                  Park              Bus Line   
50   Moore Park          Tennis Court                   Gym   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
49          Dance Studio              Dive Bar               Dog Run   
50                  Park           Yoga Studio   Egyptian Restaurant   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
49      Doner Restaurant            Donut Shop   Dumpling Restaurant   
50               Dog Run      Doner Restaurant            Donut Shop   

          9th Most Common Venue       10th Most Common Venue  
49  Eastern European Restaurant          Egyptian Restaurant  
50          Dumpling Restaurant  Eastern European Restaurant

In [153]:
Cluster3 = Toronto_merged.loc[Toronto_merged['Cluster Labels'] == 2, Toronto_merged.columns[[1] + list(range(5, Toronto_merged.shape[1]))]]

print('Cluster 3 has the following', Cluster3.shape[0],'Neighborhoods')
Cluster3

Cluster 3 has the following 25 Neighborhoods


Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
0               Regent Park           Coffee Shop       Thai Restaurant   
1              Harbourfront           Coffee Shop                  Café   
2              Queen's Park           Coffee Shop                  Café   
4                   Ryerson           Coffee Shop        Clothing Store   
5            St. James Town           Coffee Shop           Pizza Place   
7               Berczy Park           Coffee Shop                  Café   
10                 Adelaide           Coffee Shop                  Café   
11                     King           Coffee Shop                 Hotel   
13       Dovercourt Village                  Café           Pizza Place   
14        Harbourfront East           Coffee Shop                  Café   
15            Union Station           Coffee Shop                  Café   
18                  Trinity           Coffee Shop                  Café   
21  Toronto Dominion Centre           Coffee Shop                 Hotel   
22          Design Exchange           Coffee Shop                  Café   
28           Commerce Court           Coffee Shop                 Hotel   
29           Victoria Hotel           Coffee Shop           Pizza Place   
48                Runnymede           Coffee Shop                  Café   
59                Deer Park           Coffee Shop    Italian Restaurant   
60                 CN Tower                 Hotel           Coffee Shop   
61         King and Spadina           Coffee Shop                 Hotel   
62        Harbourfront West           Coffee Shop                  Café   
63            Bathurst Quay           Coffee Shop                  Café   
67           St. James Town           Coffee Shop           Pizza Place   
69     First Canadian Place           Coffee Shop                 Hotel   
71     Church and Wellesley           Coffee Shop      Sushi Restaurant   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                   Pool     Electronics Store            Beer Store   
1             Restaurant                 Hotel    Italian Restaurant   
2         Sandwich Place    Italian Restaurant   Japanese Restaurant   
4           Burger Joint      Ramen Restaurant   Japanese Restaurant   
5                   Café         Grocery Store            Playground   
7             Restaurant                 Hotel   Japanese Restaurant   
10                   Gym            Restaurant             Gastropub   
11            Restaurant                  Café    Seafood Restaurant   
13                   Bar              Bus Line            Restaurant   
14            Restaurant                 Hotel    Italian Restaurant   
15                 Hotel   Japanese Restaurant         Deli / Bodega   
18                Museum                  Park              Boutique   
21                  Café   American Restaurant            Restaurant   
22            Restaurant                 Hotel                   Gym   
28            Restaurant                  Café   American Restaurant   
29                  Café         Grocery Store            Beer Store   
48                Bakery                  Bank           Pizza Place   
59      Sushi Restaurant         Grocery Store       Thai Restaurant   
60           Pizza Place      Baseball Stadium                   Gym   
61    Italian Restaurant            Restaurant        Sandwich Place   
62            Restaurant                 Hotel    Italian Restaurant   
63                  Park                 Diner       Harbor / Marina   
67                  Café         Grocery Store            Playground   
69            Restaurant                  Café                   Gym   
71   Japanese Restaurant               Gay Bar            Restaurant   

   6th Most Common Venue 7th Most Common Venue      8th Most Common Venue  \
0             Food Truck      Sushi Restaurant                 Restaurant   
1            Pizza Place        Sandw

In [154]:
Cluster4 = Toronto_merged.loc[Toronto_merged['Cluster Labels'] == 3, Toronto_merged.columns[[1] + list(range(5, Toronto_merged.shape[1]))]]

print('Cluster 4 has the following', Cluster4.shape[0],'Neighborhoods')
Cluster4

Cluster 4 has the following 5 Neighborhoods


Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
9           Richmond                  Park        Ice Cream Shop   
16   Toronto Islands           Music Venue                  Park   
56         Rathnelly                  Park    Mexican Restaurant   
58    Forest Hill SE            Playground          Home Service   
66          Rosedale            Bike Trail            Playground   

   3rd Most Common Venue 4th Most Common Venue          5th Most Common Venue  \
9             Beer Store           Event Space               Doner Restaurant   
16       Harbor / Marina                  Café                 Farmers Market   
56     French Restaurant           Pizza Place  Vegetarian / Vegan Restaurant   
58                  Bank   Arts & Crafts Store                           Park   
66                  Park     Fish & Chips Shop            Egyptian Restaurant   

   6th Most Common Venue 7th Most Common Venue        8th Most Common Venue  \
9             Donut Shop   Dumpling Restaurant  Eastern European Restaurant   
16    Falafel Restaurant           Event Space         Ethiopian Restaurant   
56                  Café          Liquor Store           Italian Restaurant   
58           Yoga Studio   Egyptian Restaurant                      Dog Run   
66       Doctor's Office               Dog Run             Doner Restaurant   

   9th Most Common Venue 10th Most Common Venue  
9    Egyptian Restaurant      Electronics Store  
16     Electronics Store   Fast Food Restaurant  
56                   Pub              BBQ Joint  
58      Doner Restaurant             Donut Shop  
66            Donut Shop    Dumpling Restaurant

In [155]:
Cluster5 = Toronto_merged.loc[Toronto_merged['Cluster Labels'] == 4, Toronto_merged.columns[[1] + list(range(5, Toronto_merged.shape[1]))]]

print('Cluster 5 has the following', Cluster5.shape[0],'Neighborhoods')
Cluster5

Cluster 5 has the following 1 Neighborhoods


Neighborhood 1st Most Common Venue 2nd Most Common Venue  \
35   Forest Hill Road Park    Light Rail Station          Skating Rink   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
35           Supermarket          Liquor Store           Coffee Shop   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
35     Electronics Store      Doner Restaurant            Donut Shop   

   9th Most Common Venue       10th Most Common Venue  
35   Dumpling Restaurant  Eastern European Restaurant